# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-09 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 16, 25, 16, 571772, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
