# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-08 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='photos.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2019, 11, 8, 18, 42, 6, 360585, tzinfo=utc), upload_to='photos/'),
            preserve_default=False,
        ),
    ]
