# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-09 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20191108_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 9, 51, 23, 428033, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
