# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pub_date',
            new_name='date',
        ),
    ]
